/* Oneshot-Locking and Tapping-Toggle */

#define ONESHOT_TAP_TOGGLE 2
#define TAPPING_TOGGLE 2
#undef DEBOUNCE
#define DEBOUNCE 4
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_MOOD
#define RGBLIGHT_DEFAULT_SPEED -10
